name: doctors_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  colorize: ^3.0.0

  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.1
  hexcolor: ^3.0.1
  iconsax: ^0.0.8
  meta: ^1.10.0
  chat_bubbles: ^1.7.0
  path_provider: ^2.1.3
  animate_do: ^3.3.4


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # - assets/icons/
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#399cbd"
  image: "assets/images/app_icon.png"
